In [15]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import neighbors
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [16]:
file_path = '/content/drive/MyDrive/KNN/N10S10.csv'

df = pd.read_csv(file_path)
df.head()

,-0.269020,-0.274271,-0.276772,-0.280534,-0.273830,-0.281028,-0.278340,-0.281899,-0.274114,-0.275033,...,0.731363,1.087850,-0.538692,0.418131,-0.146727,-0.524564,-0.550826,0.424102,0.943884,1
0,-0.270564,-0.275361,-0.277809,-0.281082,-0.271159,-0.282111,-0.278279,-0.281899,-0.276891,-0.273932,...,-0.225476,0.612769,-0.526338,-0.551405,0.050997,1.735645,1.045268,0.100190,-0.538153,1
1,-0.271119,-0.274801,-0.278343,-0.282144,-0.273266,-0.279540,-0.272440,-0.279165,-0.277974,-0.273992,...,0.768165,1.672565,1.709689,1.400098,1.694581,-0.536847,-0.550826,1.109301,1.348075,1
2,-0.243652,-0.255094,-0.123749,-0.264757,-0.194840,-0.223202,-0.191469,-0.254143,-0.254398,-0.232493,...,-0.176408,1.843107,-0.205141,0.691591,0.471161,0.421285,-0.207052,-0.049307,-0.023727,1
3,-0.202801,-0.241096,-0.243974,-0.282722,-0.219419,-0.264523,-0.266578,-0.275889,-0.265712,-0.268987,...,-0.066003,-0.179033,-0.538692,-0.016917,-0.270305,-0.463145,-0.489438,-0.410594,-0.366678,1
4,-0.271119,-0.275361,-0.245397,0.065535,0.167238,-0.057862,-0.094508,-0.182476,-0.245605,0.203647,...,-0.495354,-0.313030,1.573798,2.319915,0.916041,0.359866,0.210388,-0.423052,1.984984,1

In [17]:
X = df.iloc[:, :-1]
y = df.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [18]:
y.value_counts()

1
0    24733
1    14261
Name: count, dtype: int64

In [22]:
def issqrt(n):
  x = n
  y = (x+1)//2
  while (y<x):
    x = y
    y = (x+n // x) //2
  return x

In [23]:
k = issqrt(len(X))
knn = neighbors.KNeighborsClassifier(n_neighbors = k)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=197)

In [24]:
y_pred = knn.predict(X_test)

In [25]:
matrix = confusion_matrix(y_test,y_pred)
accuracy = np.trace(matrix) / float(np.sum(matrix))
acc = accuracy_score(y_test, y_pred)
print(acc)
print("Confusion matrix")
print(matrix)
print("The accuracy is {:.2%}".format(accuracy))

0.9720476984228748
Confusion matrix
[[4807  152]
 [  66 2774]]
The accuracy is 97.20%

In [26]:
from sklearn.metrics import classification_report

print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.97      0.98      4959
           1       0.95      0.98      0.96      2840

    accuracy                           0.97      7799
   macro avg       0.97      0.97      0.97      7799
weighted avg       0.97      0.97      0.97      7799